# Generated by Django 4.1.2 on 2022-10-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20221013_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'СуперАдмин'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('default', 'Обычный')], default='default', max_length=100, verbose_name='Role'),
        ),
    ]
